(() => {
"use strict";

const KEY="midlifeOS_v18";
const VERSION=18;
const defaults={schemaVersion:VERSION,lang:"de",activeTab:"dashboard",entries:[],analysisRange:30,overlaySleep:true,reportRange:30,doctorNote:""};
const SYM=["hot","brain","joints","headache","palpitations"], ACUTE=["hot","anxious","headache","palpitations"];
const I={
 de:{dashboard:"Dashboard",log:"Erfassen",analysis:"Verlauf",report:"Arzt & Profil",gm:"Guten Morgen",gd:"Guten Tag",ge:"Guten Abend",noCheck:"Heute noch kein Check-in",done:"Heute erledigt ✓",acute:"Akutes Symptom erfassen",acuteSub:"Hitzewallung, Unruhe, Migräne oder Herzrasen in wenigen Sekunden.",checkin:"20-Sekunden-Check-in",checkinSub:"Leer starten, nur erfassen, was heute relevant ist.",spotlight:"Muster-Spotlight",notEnough:"Noch nicht genug Daten für ein sinnvolles Muster.",seven:"7-Tage-Überblick",sleep:"Schlaf",energy:"Energie",load:"Belastung",sleepHours:"Schlafdauer",sleepQuality:"Schlafqualität",physical:"Beschwerden",mental:"Mental",mood:"Stimmung",cycle:"Zyklus / HRT",hot:"Hitzewallung",brain:"Brain Fog",joints:"Gelenke",headache:"Kopfschmerz",anxious:"Unruhe / Panik",palpitations:"Herzrasen",veryPoor:"Sehr schlecht",poor:"Schlecht",neutral:"Okay",good:"Gut",veryGood:"Sehr gut",empty:"Leer",low:"Niedrig",steady:"Okay",high:"Gut",full:"Voll",calm:"Ruhig",exhausted:"Erschöpft",irritable:"Gereizt",anxiousMood:"Ängstlich",bleedNone:"Keine Blutung",bleedLight:"Leicht",bleedHeavy:"Stark",spotting:"Schmierblutung",hrt:"HRT/HET heute eingenommen",save:"Check-in speichern",savedToast:"Tages-Check-in gespeichert ✓",acuteSaved:"Akut-Symptom erfasst ✓",intensity:"Intensität",mild:"Leicht",moderate:"Mittel",strong:"Stark",corr:"Schlaf überlagern",history:"Einträge",edit:"Bearbeiten",del:"Löschen",noData:"Erfasse deine ersten Tage, um deinen Verlauf als Kurve zu sehen.",symptom:"Symptom",frequency:"Häufigkeit",average:"Ø Intensität",peak:"Peak-Zeit",reportTitle:"Arzt-Zusammenfassung",period:"Erfassungszeitraum",sleepTrend:"Schlaftrend",bleedings:"Blutungen / Schmierblutungen",hrtConsistency:"HRT/HET-Dokumentation",patientNote:"Eigene Notizen für das Arztgespräch",patientPlaceholder:"Eigene Fragen oder Beobachtungen für das Arztgespräch notieren...",doctorField:"Notizen für Arzt / Ärztin",print:"Report drucken / als PDF sichern",data:"Datenverwaltung",json:"JSON",csv:"CSV",deleteAll:"Alle Daten sicher löschen",confirmDelete:"Alle lokalen Einträge wirklich löschen?",cancel:"Abbrechen",deleteNow:"Daten löschen",medical:"Midlife OS zeigt Beobachtungen aus deinen Einträgen. Es stellt keine Diagnose und ersetzt keine medizinische Beratung.",observe:"Beobachtung",possible:"Möglicher Zusammenhang",insufficient:"Für diese Beobachtung sind noch zu wenige vergleichbare Tage vorhanden.",acuteEdit:"Akut-Eintrag bearbeiten"},
 en:{dashboard:"Dashboard",log:"Log",analysis:"History",report:"Doctor & Profile",gm:"Good morning",gd:"Good afternoon",ge:"Good evening",noCheck:"No check-in yet today",done:"Today complete ✓",acute:"Log acute symptom",acuteSub:"Capture a hot flash, restlessness, migraine or palpitations in seconds.",checkin:"20-second check-in",checkinSub:"Start empty and log only what matters today.",spotlight:"Pattern spotlight",notEnough:"Not enough data yet for a meaningful pattern.",seven:"7-day overview",sleep:"Sleep",energy:"Energy",load:"Symptom load",sleepHours:"Sleep duration",sleepQuality:"Sleep quality",physical:"Symptoms",mental:"Mental",mood:"Mood",cycle:"Cycle / HRT",hot:"Hot flash",brain:"Brain fog",joints:"Joints",headache:"Headache",anxious:"Restlessness / panic",palpitations:"Palpitations",veryPoor:"Very poor",poor:"Poor",neutral:"Okay",good:"Good",veryGood:"Very good",empty:"Empty",low:"Low",steady:"Okay",high:"Good",full:"Full",calm:"Calm",exhausted:"Exhausted",irritable:"Irritable",anxiousMood:"Anxious",bleedNone:"No bleeding",bleedLight:"Light",bleedHeavy:"Heavy",spotting:"Spotting",hrt:"HRT/MHT taken today",save:"Save check-in",savedToast:"Daily check-in saved ✓",acuteSaved:"Acute symptom captured ✓",intensity:"Intensity",mild:"Mild",moderate:"Moderate",strong:"Strong",corr:"Overlay sleep",history:"Entries",edit:"Edit",del:"Delete",noData:"Log your first days to see your history as a chart.",symptom:"Symptom",frequency:"Frequency",average:"Avg intensity",peak:"Peak time",reportTitle:"Doctor summary",period:"Tracking period",sleepTrend:"Sleep trend",bleedings:"Bleeding / spotting",hrtConsistency:"HRT/MHT documentation",patientNote:"Your notes for the appointment",patientPlaceholder:"Add your own questions or observations for the appointment...",doctorField:"Clinician notes",print:"Print report / save as PDF",data:"Data management",json:"JSON",csv:"CSV",deleteAll:"Securely delete all data",confirmDelete:"Really delete all local entries?",cancel:"Cancel",deleteNow:"Delete data",medical:"Midlife OS shows observations from your entries. It does not diagnose and does not replace medical advice.",observe:"Observation",possible:"Possible association",insufficient:"There are not enough comparable days for this observation yet.",acuteEdit:"Edit acute entry"}
};

const blank=()=>({sleepBand:"",sleepHours:0,sleepQuality:0,energy:0,symptoms:{},mood:"",bleeding:"",hrtTaken:false});
function uid(){return crypto?.randomUUID?.()||("e_"+Date.now()+"_"+Math.random().toString(16).slice(2))}
function clamp(v,a,b,d=0){const n=Number(v);return Number.isFinite(n)?Math.max(a,Math.min(b,n)):d}
function normalize(e){const symptoms={};if(e?.symptoms&&typeof e.symptoms==="object")for(const [k,v] of Object.entries(e.symptoms)){if(SYM.includes(k))symptoms[k]=clamp(v,1,3,1)}return{id:String(e?.id||uid()),ts:new Date(e?.ts||Date.now()).toISOString(),type:e?.type==="acute"?"acute":"checkin",sleepBand:typeof e?.sleepBand==="string"?e.sleepBand:"",sleepHours:clamp(e?.sleepHours,0,12),sleepQuality:clamp(e?.sleepQuality,0,5),energy:clamp(e?.energy,0,5),symptoms,mood:["calm","exhausted","irritable","anxiousMood"].includes(e?.mood)?e.mood:"",bleeding:["bleedNone","bleedLight","bleedHeavy","spotting"].includes(e?.bleeding)?e.bleeding:"",hrtTaken:!!e?.hrtTaken,acuteSymptom:ACUTE.includes(e?.acuteSymptom)?e.acuteSymptom:"",intensity:clamp(e?.intensity,1,3,2)}}

class AppStore{
 constructor(){this.listeners=new Set();this.state=this.load()}
 parse(v){try{return JSON.parse(v)}catch{return null}}
 subscribe(fn){this.listeners.add(fn);return()=>this.listeners.delete(fn)}
 emit(){this.listeners.forEach(fn=>fn(this.state))}
 persist(){try{this.state.schemaVersion=VERSION;localStorage.setItem(KEY,JSON.stringify(this.state))}catch{}}
 update(fn){fn(this.state);this.persist();this.emit()}
 load(){const current=this.parse(localStorage.getItem(KEY));if(current?.schemaVersion===VERSION){current.entries=Array.isArray(current.entries)?current.entries.map(normalize):[];return{...structuredClone(defaults),...current}}const next=structuredClone(defaults);for(const k of ["midlifeOS_v17","midlifeOS_v15","midlifeOS_v14","midlifeOS_v13","midlifeOS_v12"]){const old=this.parse(localStorage.getItem(k));if(!old)continue;if(["de","en"].includes(old.lang))next.lang=old.lang;if(old.doctorNote)next.doctorNote=old.doctorNote;if(Array.isArray(old.entries))for(const e of old.entries){if(e.type==="acute"||e.kind==="acute-hot-flash")next.entries.push(normalize({id:e.id||uid(),ts:e.ts,type:"acute",acuteSymptom:e.acuteSymptom||"hot",intensity:e.intensity||2}));else{const symptoms={};if(e.symptoms&&typeof e.symptoms==="object")Object.assign(symptoms,e.symptoms);if(Array.isArray(e.physical))for(const id of e.physical){if(SYM.includes(id))symptoms[id]=1}if(e.brainFog==="fogLight")symptoms.brain=1;if(e.brainFog==="fogYes")symptoms.brain=2;next.entries.push(normalize({id:e.id||uid(),ts:e.ts,type:"checkin",sleepBand:e.sleepBand||"",sleepHours:e.sleepHours||0,sleepQuality:e.sleepQuality||0,energy:e.energy||0,symptoms,mood:e.mood||"",bleeding:e.bleeding||"",hrtTaken:!!e.hrtTaken}))}}}localStorage.setItem(KEY,JSON.stringify(next));return next}
}
const store=new AppStore();
let draft=blank(),editing=null,modal=null;
const S=()=>store.state, tr=k=>I[S().lang][k]||k, locale=()=>S().lang==="de"?"de-DE":"en-GB";
function sameDay(ts,d=new Date()){const x=new Date(ts);return x.getFullYear()===d.getFullYear()&&x.getMonth()===d.getMonth()&&x.getDate()===d.getDate()}
function cut(days){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-(days-1));return d}
function range(days){const c=cut(days);return S().entries.filter(e=>new Date(e.ts)>=c).sort((a,b)=>new Date(a.ts)-new Date(b.ts))}
function today(){return S().entries.filter(e=>sameDay(e.ts)).sort((a,b)=>new Date(b.ts)-new Date(a.ts))}
function fmtD(x){return new Date(x).toLocaleDateString(locale(),{day:"2-digit",month:"short",year:"numeric"})}
function fmtT(x){return new Date(x).toLocaleTimeString(locale(),{hour:"2-digit",minute:"2-digit"})}
function greet(){const h=new Date().getHours();return h<11?tr("gm"):h<18?tr("gd"):tr("ge")}
function avg(a){return a.length?a.reduce((x,y)=>x+y,0)/a.length:0}
function has(e,id){return e.type==="acute"?e.acuteSymptom===id:!!e.symptoms[id]}
function intensity(e,id){return e.type==="acute"&&e.acuteSymptom===id?e.intensity:(e.symptoms[id]||0)}
function loadScore(e){return e.type==="acute"?e.intensity:Object.values(e.symptoms).reduce((a,b)=>a+b,0)}
function stats(es){const m={};for(const e of es){const ids=e.type==="acute"&&e.acuteSymptom?[e.acuteSymptom]:Object.keys(e.symptoms);for(const id of ids){m[id]??={count:0,sum:0};m[id].count++;m[id].sum+=intensity(e,id)}}return Object.entries(m).map(([id,v])=>({id,count:v.count,avg:v.sum/v.count})).sort((a,b)=>b.count-a.count||b.avg-a.avg)}
function top(es){return stats(es)[0]||null}
function peak(es,id){const hs=es.filter(e=>has(e,id)).map(e=>new Date(e.ts).getHours());if(!hs.length)return"—";const b=[[0,6],[6,12],[12,18],[18,24]],n=S().lang==="de"?["Nacht","Morgen","Nachmittag","Abend"]:["Night","Morning","Afternoon","Evening"],c=b.map(([a,z])=>hs.filter(h=>h>=a&&h<z).length);return n[c.indexOf(Math.max(...c))]}
function rangeLabel(n){return S().lang==="de"?`${n} Tage`:`${n} days`}
function severityName(n){return ["",tr("mild"),tr("moderate"),tr("strong")][n]||"—"}
function escapeHtml(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}

function insight(days){const es=range(days),cs=es.filter(e=>e.type==="checkin"&&e.sleepHours>0),hots=es.filter(e=>has(e,"hot"));if(cs.length<5||hots.length<3)return{title:tr("observe"),text:tr("notEnough")};const low=new Set(cs.filter(e=>e.sleepHours<6).map(e=>e.ts.slice(0,10))),good=new Set(cs.filter(e=>e.sleepHours>=6).map(e=>e.ts.slice(0,10)));if(low.size<2||good.size<2)return{title:tr("observe"),text:tr("insufficient")};const mean=set=>avg(es.filter(e=>set.has(e.ts.slice(0,10))&&has(e,"hot")).map(e=>intensity(e,"hot")));const a=mean(low),b=mean(good);if(!a||!b)return{title:tr("observe"),text:tr("insufficient")};return{title:tr("possible"),text:S().lang==="de"?`An Tagen mit < 6 h Schlaf lag die dokumentierte Hitzewallungs-Intensität bei Ø ${a.toFixed(1)}, an Tagen mit ≥ 6 h Schlaf bei Ø ${b.toFixed(1)}. Beobachtung, keine Ursache-Wirkung-Aussage.`:`On days with < 6 h sleep, documented hot-flash intensity averaged ${a.toFixed(1)} versus ${b.toFixed(1)} on days with ≥ 6 h sleep. Observation, not a causal claim.`}}

function icon(k){const p={home:'<path d="M4 11.5 12 5l8 6.5V20H4z"/><path d="M9 20v-6h6v6"/>',plus:'<path d="M12 5v14M5 12h14"/>',trend:'<path d="M4 17l5-5 4 3 7-8"/>',report:'<path d="M6 3h9l3 3v15H6z"/><path d="M15 3v4h4M9 12h6M9 16h6"/>'}[k];return`<svg viewBox="0 0 24 24">${p}</svg>`}
function nav(id,ic){return`<button data-tab="${id}" class="${S().activeTab===id?"active":""}">${icon(ic)}<span>${tr(id)}</span></button>`}
function render(){document.documentElement.lang=S().lang;document.getElementById("app").innerHTML=`<div class="shell"><header class="topbar"><div class="brand">Midlife <b>OS.</b></div><div class="lang"><button data-lang="de" class="${S().lang==="de"?"active":""}">DE</button><button data-lang="en" class="${S().lang==="en"?"active":""}">EN</button></div></header><main class="view">${view()}</main><nav class="bottom-nav">${nav("dashboard","home")}${nav("log","plus")}${nav("analysis","trend")}${nav("report","report")}</nav></div>`;bind();if(modal)showModal()}
function view(){return S().activeTab==="log"?logView():S().activeTab==="analysis"?analysisView():S().activeTab==="report"?reportView():dashboardView()}

function dashboardView(){const t=today(),check=t.find(e=>e.type==="checkin"),week=range(7),cs=week.filter(e=>e.type==="checkin"),i=insight(14);return`<div class="stack"><section class="card"><div class="eyebrow">${tr("dashboard")}</div><h1 style="margin-top:4px">${greet()}</h1><div class="sub">${check?tr("done"):tr("noCheck")}</div></section><div class="action-grid"><button class="action sos" id="acute"><strong>${tr("acute")}</strong><small>${tr("acuteSub")}</small></button><button class="action" data-go="log"><strong>${tr("checkin")}</strong><small>${tr("checkinSub")}</small></button></div><section class="card"><div class="eyebrow">${tr("spotlight")}</div><div class="insight" style="margin-top:10px"><strong>${i.title}</strong>${i.text}</div></section><section class="card"><div class="row-top"><div><div class="eyebrow">${tr("seven")}</div><h2>${week.length} ${S().lang==="de"?"Einträge":"entries"}</h2></div><span class="pill">7D</span></div><div class="metric-grid" style="margin-top:10px"><div class="metric"><span>${tr("sleep")}</span><strong>${metric(avg(cs.map(e=>e.sleepQuality).filter(Boolean)))}</strong></div><div class="metric"><span>${tr("energy")}</span><strong>${metric(avg(cs.map(e=>e.energy).filter(Boolean)))}</strong></div><div class="metric"><span>${tr("load")}</span><strong>${metric(avg(week.map(loadScore)))}</strong></div></div><div class="chart-shell">${trendChart(7,null,false)}</div></section></div>`}
function metric(v){return v?v.toFixed(1):"—"}

function logView(){return`<div class="stack"><div><div class="eyebrow">${tr("log")}</div><h1>${editing?tr("edit"):tr("checkin")}</h1><p class="sub">${tr("checkinSub")}</p></div><section class="card section"><div class="eyebrow">${tr("sleep")}</div><div><div class="row"><strong>${tr("sleepHours")}</strong><span class="pill">${draft.sleepBand||"—"}</span></div><div class="segmented" style="margin-top:8px">${[["<6h",5],["6–7h",6.5],["7–8h",7.5],[">8h",9]].map(([label,h])=>`<button data-sleep="${label}:${h}" class="${draft.sleepBand===label?"active":""}">${label}</button>`).join("")}</div></div>${qualityBlock("sleepQuality",tr("sleepQuality"),["veryPoor","poor","neutral","good","veryGood"])}${qualityBlock("energy",tr("energy"),["empty","low","steady","high","full"])}</section><section class="card section"><div class="eyebrow">${tr("physical")}</div><div class="chips">${SYM.map(id=>`<button class="chip ${draft.symptoms[id]?"active":""}" data-sym="${id}">${tr(id)}</button>`).join("")}</div>${Object.keys(draft.symptoms).map(id=>`<div class="symptom-editor"><div class="row"><strong>${tr(id)}</strong><span class="pill">${severityName(draft.symptoms[id])}</span></div><div class="intensity-row">${[1,2,3].map(n=>`<button data-sev="${id}:${n}" class="${draft.symptoms[id]===n?"active":""}">${severityName(n)}</button>`).join("")}</div></div>`).join("")}</section><section class="card section"><div class="eyebrow">${tr("mental")}</div><div><strong>${tr("mood")}</strong><div class="segmented" style="margin-top:8px">${["calm","exhausted","irritable","anxiousMood"].map(x=>`<button data-mood="${x}" class="${draft.mood===x?"active":""}">${tr(x)}</button>`).join("")}</div></div></section><section class="card section"><div class="eyebrow">${tr("cycle")}</div><div class="segmented" style="margin-top:2px">${["bleedNone","bleedLight","bleedHeavy","spotting"].map(x=>`<button data-bleed="${x}" class="${draft.bleeding===x?"active":""}">${tr(x)}</button>`).join("")}</div><div class="toggle-row"><strong>${tr("hrt")}</strong><button class="toggle ${draft.hrtTaken?"on":""}" id="hrt"><i></i></button></div></section><button class="primary" id="saveEntry">${tr("save")}</button></div>`}
function qualityBlock(key,label,labels){return`<div><div class="row"><strong>${label}</strong><span class="pill">${draft[key]?draft[key]+"/5":"—"}</span></div><div class="segmented five" style="margin-top:8px">${labels.map((x,i)=>`<button data-q="${key}:${i+1}" class="${draft[key]===i+1?"active":""}">${tr(x)}</button>`).join("")}</div></div>`}

function analysisView(){const es=range(S().analysisRange),tp=top(es),i=insight(S().analysisRange);return`<div class="stack"><div><div class="eyebrow">${tr("analysis")}</div><h1>${S().lang==="de"?"Muster statt Datenmüll":"Patterns, not data clutter"}</h1><p class="sub">${tr("medical")}</p></div><div class="tabs">${[7,30,90].map(n=>`<button data-range="${n}" class="${S().analysisRange===n?"active":""}">${rangeLabel(n)}</button>`).join("")}</div><section class="card"><div class="row-top"><div><div class="eyebrow">${tr("spotlight")}</div><h2>${tp?tr(tp.id):tr("noData")}</h2></div><span class="pill">${es.length}</span></div><div class="correlation" style="margin-top:8px"><label>${tr("corr")}</label><button class="toggle ${S().overlaySleep?"on":""}" id="overlay"><i></i></button></div><div class="chart-shell">${trendChart(S().analysisRange,tp?.id||null,S().overlaySleep)}</div></section><div class="insight"><strong>${i.title}</strong>${i.text}</div><section class="card"><div class="eyebrow">${tr("history")}</div><div class="list" style="margin-top:10px">${es.length?[...es].reverse().map(entryCard).join(""):`<div class="empty">${tr("noData")}</div>`}</div></section></div>`}

function entryCard(e){const badges=[];if(e.type==="acute")badges.push(`<span class="badge symptom">${tr(e.acuteSymptom)}: ${severityName(e.intensity)}</span>`);else{for(const [id,n] of Object.entries(e.symptoms))badges.push(`<span class="badge symptom">${tr(id)}: ${severityName(n)}</span>`);if(e.mood)badges.push(`<span class="badge mood">${tr("mood")}: ${tr(e.mood)}</span>`);if(e.sleepBand)badges.push(`<span class="badge meta">${tr("sleep")}: ${e.sleepBand}</span>`);if(e.bleeding)badges.push(`<span class="badge meta">${tr(e.bleeding)}</span>`);if(e.hrtTaken)badges.push(`<span class="badge meta">HRT ✓</span>`)}return`<div class="entry"><div class="entry-head"><span class="entry-time">${fmtT(e.ts)}</span><span class="entry-date">${fmtD(e.ts)}</span></div><div class="badges">${badges.join("")||`<span class="badge meta">—</span>`}</div><div class="entry-actions"><button data-edit="${e.id}">${tr("edit")}</button><button class="danger" data-del="${e.id}">${tr("del")}</button></div></div>`}

function reportView(){const es=range(S().reportRange),st=stats(es),cs=es.filter(e=>e.type==="checkin"),bleed=cs.filter(e=>e.bleeding&&e.bleeding!=="bleedNone"),hrt=cs.filter(e=>e.hrtTaken).length;return`<div class="stack print-report"><div><div class="eyebrow">${tr("report")}</div><h1>${tr("reportTitle")}</h1><p class="sub">${tr("medical")}</p></div><div class="tabs no-print">${[30,60,90].map(n=>`<button data-report-range="${n}" class="${S().reportRange===n?"active":""}">${rangeLabel(n)}</button>`).join("")}</div><section class="card"><div class="row"><div><div class="eyebrow">${tr("period")}</div><h2>${fmtD(cut(S().reportRange))} – ${fmtD(new Date())}</h2></div><span class="pill">${es.length}</span></div></section><section class="card"><table class="report-table"><thead><tr><th>${tr("symptom")}</th><th>${tr("frequency")}</th><th>${tr("average")}</th><th>${tr("peak")}</th></tr></thead><tbody>${st.length?st.slice(0,5).map(x=>`<tr><td>${tr(x.id)}</td><td>${x.count}</td><td>${x.avg.toFixed(1)}</td><td>${peak(es,x.id)}</td></tr>`).join(""):`<tr><td colspan="4">${tr("noData")}</td></tr>`}</tbody></table></section><section class="card profile-grid"><div class="profile-row"><strong>${tr("sleepTrend")}</strong><small>${cs.length?`${tr("sleepHours")}: ${metric(avg(cs.map(e=>e.sleepHours).filter(Boolean)))}h · ${tr("sleepQuality")}: ${metric(avg(cs.map(e=>e.sleepQuality).filter(Boolean)))}/5`:tr("noData")}</small></div><div class="profile-row"><strong>${tr("bleedings")}</strong><small>${bleed.length}</small></div><div class="profile-row"><strong>${tr("hrtConsistency")}</strong><small>${cs.length?`${hrt}/${cs.length} ${S().lang==="de"?"Check-ins dokumentiert":"check-ins documented"}`:tr("noData")}</small></div></section><section class="card"><label class="eyebrow" for="doctorNote">${tr("patientNote")}</label><textarea class="notes" id="doctorNote" placeholder="${tr("patientPlaceholder")}">${escapeHtml(S().doctorNote||"")}</textarea></section><section class="print-clinician-note"><div class="eyebrow">${tr("doctorField")}</div><div class="line"></div></section><button class="primary no-print" id="print">${tr("print")}</button><section class="card no-print"><div class="eyebrow">${tr("data")}</div><div class="export-grid" style="margin-top:10px"><button id="json">${tr("json")}</button><button id="csv">${tr("csv")}</button></div><button class="danger-link" id="deleteAll">${tr("deleteAll")}</button></section></div>`}

function trendChart(days,symptomId,overlaySleep){const start=cut(days),series=[];for(let i=0;i<days;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=d.toISOString().slice(0,10),es=S().entries.filter(e=>e.ts.slice(0,10)===key);let val=0;if(symptomId){const vals=es.filter(e=>has(e,symptomId)).map(e=>intensity(e,symptomId));val=vals.length?Math.max(...vals):0}else{const vals=[];for(const e of es){if(e.type==="acute")vals.push(e.intensity);else vals.push(...Object.values(e.symptoms))}val=vals.length?Math.max(...vals):0}const checks=es.filter(e=>e.type==="checkin"),sleep=avg(checks.map(e=>e.sleepQuality).filter(Boolean));series.push({d,val,sleep})}if(!series.some(x=>x.val>0))return`<div class="chart-empty">${tr("noData")}</div>`;const w=360,h=190,left=28,right=10,top=18,bottom=34,plotW=w-left-right,plotH=h-top-bottom,barW=Math.max(4,Math.min(22,plotW/series.length*.55));const xs=i=>left+(i+.5)*(plotW/series.length),ys=v=>top+plotH-(v/3)*plotH;let g="";for(let v=1;v<=3;v++){const y=ys(v);g+=`<line class="grid-line" x1="${left}" y1="${y}" x2="${w-right}" y2="${y}"/><text class="axis-text" x="8" y="${y+3}">${v}</text>`}let bars="",labels="";const step=Math.max(1,Math.ceil(series.length/7));series.forEach((x,i)=>{if(x.val>0){const y=ys(x.val),height=top+plotH-y;bars+=`<rect class="bar" x="${xs(i)-barW/2}" y="${y}" width="${barW}" height="${height}" rx="4"/><text class="value-text" x="${xs(i)}" y="${Math.max(10,y-4)}" text-anchor="middle">${x.val}</text>`}if(i%step===0||i===series.length-1)labels+=`<text class="axis-text" x="${xs(i)}" y="${h-10}" text-anchor="middle">${x.d.toLocaleDateString(locale(),{weekday:"short"})}</text>`});let sleep="";if(overlaySleep&&series.some(x=>x.sleep>0)){const pts=series.map((x,i)=>`${xs(i)},${top+plotH-(x.sleep/5)*plotH}`).join(" ");sleep=`<polyline class="sleep-line" points="${pts}"/>${series.filter(x=>x.sleep>0).map((x,i)=>`<circle class="point" cx="${xs(i)}" cy="${top+plotH-(x.sleep/5)*plotH}" r="2.5"/>`).join("")}`}return`<svg class="trend-svg" viewBox="0 0 ${w} ${h}" role="img" aria-label="Trend chart">${g}${bars}${sleep}${labels}</svg>`}

function bind(){document.querySelectorAll("[data-lang]").forEach(b=>b.onclick=()=>store.update(s=>s.lang=b.dataset.lang));document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{store.update(s=>s.activeTab=b.dataset.tab);window.scrollTo({top:0,behavior:"smooth"})});document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>store.update(s=>s.activeTab=b.dataset.go));document.getElementById("acute")?.addEventListener("click",()=>openAcute());document.querySelectorAll("[data-sleep]").forEach(b=>b.onclick=()=>{const[label,h]=b.dataset.sleep.split(":");draft.sleepBand=label;draft.sleepHours=+h;render()});document.querySelectorAll("[data-q]").forEach(b=>b.onclick=()=>{const[k,n]=b.dataset.q.split(":");draft[k]=+n;render()});document.querySelectorAll("[data-sym]").forEach(b=>b.onclick=()=>{const id=b.dataset.sym;if(draft.symptoms[id])delete draft.symptoms[id];else draft.symptoms[id]=1;render()});document.querySelectorAll("[data-sev]").forEach(b=>b.onclick=()=>{const[id,n]=b.dataset.sev.split(":");draft.symptoms[id]=+n;render()});document.querySelectorAll("[data-mood]").forEach(b=>b.onclick=()=>{draft.mood=b.dataset.mood;render()});document.querySelectorAll("[data-bleed]").forEach(b=>b.onclick=()=>{draft.bleeding=b.dataset.bleed;render()});document.getElementById("hrt")?.addEventListener("click",()=>{draft.hrtTaken=!draft.hrtTaken;render()});document.getElementById("saveEntry")?.addEventListener("click",saveEntry);document.querySelectorAll("[data-range]").forEach(b=>b.onclick=()=>store.update(s=>s.analysisRange=+b.dataset.range));document.getElementById("overlay")?.addEventListener("click",()=>store.update(s=>s.overlaySleep=!s.overlaySleep));document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>editEntry(b.dataset.edit));document.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>deleteEntry(b.dataset.del));document.querySelectorAll("[data-report-range]").forEach(b=>b.onclick=()=>store.update(s=>s.reportRange=+b.dataset.reportRange));document.getElementById("doctorNote")?.addEventListener("input",e=>{S().doctorNote=e.target.value;store.persist()});document.getElementById("print")?.addEventListener("click",()=>window.print());document.getElementById("json")?.addEventListener("click",exportJson);document.getElementById("csv")?.addEventListener("click",exportCsv);document.getElementById("deleteAll")?.addEventListener("click",openDeleteAll)}
function saveEntry(){if(!draft.sleepBand&&!draft.sleepQuality&&!draft.energy&&!Object.keys(draft.symptoms).length&&!draft.mood&&!draft.bleeding&&!draft.hrtTaken){toast(S().lang==="de"?"Bitte mindestens einen Wert auswählen.":"Please choose at least one value.");return}const old=editing?S().entries.find(e=>e.id===editing):null,entry=normalize({id:editing||uid(),ts:old?.ts||new Date(),type:"checkin",...draft});store.update(s=>{if(editing)s.entries=s.entries.map(x=>x.id===editing?entry:x);else s.entries.push(entry)});draft=blank();editing=null;toast(tr("savedToast"));setTimeout(()=>store.update(s=>s.activeTab="dashboard"),400)}
function editEntry(id){const e=S().entries.find(x=>x.id===id);if(!e)return;if(e.type==="acute"){modal={type:"acute",editId:id,symptom:e.acuteSymptom,intensity:e.intensity};showModal();return}editing=id;draft={sleepBand:e.sleepBand,sleepHours:e.sleepHours,sleepQuality:e.sleepQuality,energy:e.energy,symptoms:{...e.symptoms},mood:e.mood,bleeding:e.bleeding,hrtTaken:e.hrtTaken};store.update(s=>s.activeTab="log")}
function deleteEntry(id){store.update(s=>s.entries=s.entries.filter(e=>e.id!==id));toast(S().lang==="de"?"Eintrag gelöscht.":"Entry deleted.")}
function openAcute(){modal={type:"acute",editId:null,symptom:"",intensity:2};showModal()}
function openDeleteAll(){modal={type:"deleteAll"};showModal()}
function showModal(){document.querySelector(".backdrop")?.remove();const w=document.createElement("div");w.className="backdrop";if(modal.type==="acute")w.innerHTML=`<section class="sheet"><div class="grabber"></div><div class="sheet-head"><div><div class="eyebrow">${modal.editId?tr("acuteEdit"):tr("acute")}</div><h2>${S().lang==="de"?"Was passiert gerade?":"What is happening now?"}</h2></div><button class="close" id="close">×</button></div><div class="chips" style="margin-top:12px">${ACUTE.map(id=>`<button class="chip ${modal.symptom===id?"active":""}" data-acute="${id}">${tr(id)}</button>`).join("")}</div><div class="eyebrow" style="margin-top:14px">${tr("intensity")}</div><div class="intensity-row">${[1,2,3].map(n=>`<button data-int="${n}" class="${modal.intensity===n?"active":""}">${severityName(n)}</button>`).join("")}</div><button class="primary" id="saveAcute" style="margin-top:14px">${tr("save")}</button></section>`;else w.innerHTML=`<section class="sheet"><div class="grabber"></div><h2>${tr("deleteAll")}</h2><p class="sub">${tr("confirmDelete")}</p><div class="export-grid" style="margin-top:14px"><button id="cancel">${tr("cancel")}</button><button id="confirm" style="color:var(--danger)">${tr("deleteNow")}</button></div></section>`;document.body.appendChild(w);w.onclick=e=>{if(e.target===w){modal=null;w.remove()}};document.getElementById("close")?.addEventListener("click",()=>{modal=null;w.remove()});document.querySelectorAll("[data-acute]").forEach(b=>b.onclick=()=>{modal.symptom=b.dataset.acute;showModal()});document.querySelectorAll("[data-int]").forEach(b=>b.onclick=()=>{modal.intensity=+b.dataset.int;showModal()});document.getElementById("saveAcute")?.addEventListener("click",()=>{if(!modal.symptom)return;const e=normalize({id:modal.editId||uid(),ts:modal.editId?(S().entries.find(x=>x.id===modal.editId)?.ts||new Date()):new Date(),type:"acute",acuteSymptom:modal.symptom,intensity:modal.intensity});store.update(s=>{if(modal.editId)s.entries=s.entries.map(x=>x.id===modal.editId?e:x);else s.entries.push(e)});modal=null;w.remove();toast(tr("acuteSaved"));render()});document.getElementById("cancel")?.addEventListener("click",()=>{modal=null;w.remove()});document.getElementById("confirm")?.addEventListener("click",()=>{const lang=S().lang;store.state={...structuredClone(defaults),lang};store.persist();draft=blank();editing=null;modal=null;w.remove();render();toast(lang==="de"?"Alle Daten gelöscht.":"All data deleted.")})}
function toast(msg){document.querySelector(".toast")?.remove();const e=document.createElement("div");e.className="toast";e.textContent=msg;document.body.appendChild(e);navigator.vibrate?.(20);setTimeout(()=>e.remove(),1600)}
function download(name,content,type){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportJson(){download(`midlife-os-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(S(),null,2),"application/json")}
function csvCell(v){const s=String(v??"");return/[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
function exportCsv(){const h=["id","timestamp","type","sleepBand","sleepHours","sleepQuality","energy","symptoms","mood","bleeding","hrtTaken","acuteSymptom","intensity"],rows=S().entries.map(e=>h.map(k=>csvCell(k==="symptoms"?Object.entries(e.symptoms).map(([a,b])=>`${a}:${b}`).join("|"):e[k])).join(","));download(`midlife-os-${new Date().toISOString().slice(0,10)}.csv`,[h.join(","),...rows].join("\n"),"text/csv;charset=utf-8")}
store.subscribe(()=>render());render();
})();