(() => {
"use strict";

const KEY="midlifeOS_v13";
const VERSION=13;
const defaultState={schemaVersion:VERSION,lang:"de",activeTab:"dashboard",entries:[],reportRange:30,doctorNote:""};
let state=load();
let draft=blankDraft();
let sosChoice="";
let breathingTimer=null;
let breathingRunning=false;

const symptoms=[
  {id:"hot",de:"Hitzewallung / Nachtschweiß",en:"Hot flash / night sweat"},
  {id:"joints",de:"Gelenkbeschwerden",en:"Joint discomfort"},
  {id:"headache",de:"Kopfschmerz / Migräne",en:"Headache / migraine"},
  {id:"palpitations",de:"Herzrasen",en:"Palpitations"},
  {id:"bleeding",de:"Schmierblutung",en:"Spotting"}
];

const text={
 de:{dashboard:"Dashboard",log:"Erfassen",tools:"Wissen & Tools",report:"Verlauf & Arzt",greetMorning:"Guten Morgen",greetDay:"Guten Tag",greetEvening:"Guten Abend",noCheck:"Noch kein Check-in für heute",checked:"Heute bereits eingetragen",sos:"SOS / Akut-Symptom",sosSub:"In wenigen Sekunden ein Ereignis festhalten.",checkin:"Tages-Check-in",checkinSub:"Unter 30 Sekunden, ohne Vorbelegung.",week:"Wochen-Überblick",trend:"Mini-Trend",tip:"Tages-Impuls",sleepEnergy:"Schlaf & Energie",sleep:"Schlaf",energy:"Energie",moodFocus:"Stimmung & mentaler Fokus",mood:"Stimmung",focus:"Fokus",physical:"Physische Beschwerden",save:"Eintrag speichern",saved:"Eintrag für heute gesichert ✓",none:"Keine Auswahl",chooseSymptom:"Akut-Symptom wählen",saveSos:"Akut-Ereignis speichern",sosSaved:"Akut-Ereignis gespeichert ✓",close:"Schließen",breathe:"4-7-8 Atem-Taktgeber",breatheSub:"Eine ruhige Atemübung zur Entspannung. Stoppe, wenn dir schwindlig oder unwohl wird.",start:"Starten",stop:"Stoppen",inhale:"Einatmen",hold:"Halten",exhale:"Ausatmen",evidence:"Wissens-Snacks",analysis:"Verlauf & Analyse",days30:"30 Tage",days60:"60 Tage",days90:"90 Tage",symptom:"Symptom",frequency:"Häufigkeit",avg:"Ø Intensität",period:"Zeitraum",entries:"Einträge",cycle:"Zyklus / Blutungen",patientNotes:"Eigene Notiz",doctorNotes:"Freifeld für Arzt / Ärztin",print:"Arzt-Report drucken / als PDF sichern",noData:"Noch keine Daten vorhanden.",medical:"Midlife OS unterstützt beim Beobachten und Strukturieren. Es stellt keine Diagnose und ersetzt keine medizinische Beratung."},
 en:{dashboard:"Dashboard",log:"Log",tools:"Evidence & Tools",report:"History & Doctor",greetMorning:"Good morning",greetDay:"Good afternoon",greetEvening:"Good evening",noCheck:"No check-in yet today",checked:"Already checked in today",sos:"SOS / Acute symptom",sosSub:"Capture an event in a few seconds.",checkin:"Daily check-in",checkinSub:"Under 30 seconds, with no preselected answers.",week:"Weekly overview",trend:"Mini trend",tip:"Daily insight",sleepEnergy:"Sleep & energy",sleep:"Sleep",energy:"Energy",moodFocus:"Mood & mental focus",mood:"Mood",focus:"Focus",physical:"Physical symptoms",save:"Save check-in",saved:"Today's entry saved ✓",none:"No selection",chooseSymptom:"Choose acute symptom",saveSos:"Save acute event",sosSaved:"Acute event saved ✓",close:"Close",breathe:"4-7-8 breathing guide",breatheSub:"A gentle breathing exercise for relaxation. Stop if you feel dizzy or unwell.",start:"Start",stop:"Stop",inhale:"Inhale",hold:"Hold",exhale:"Exhale",evidence:"Evidence snacks",analysis:"History & analysis",days30:"30 days",days60:"60 days",days90:"90 days",symptom:"Symptom",frequency:"Frequency",avg:"Avg intensity",period:"Period",entries:"Entries",cycle:"Cycle / bleeding",patientNotes:"Your note",doctorNotes:"Clinician notes",print:"Print doctor report / save as PDF",noData:"No data yet.",medical:"Midlife OS helps organize observations. It does not diagnose and does not replace medical advice."}
};

const tips={
 de:["Koffein kann bei manchen Menschen Hitzewallungen oder Schlafprobleme verstärken. Beobachte, ob du bei dir einen Zusammenhang erkennst.","Regelmäßige Bewegung kann Schlaf, Stimmung und allgemeines Wohlbefinden unterstützen. Entscheidend ist eine Form, die im Alltag realistisch bleibt.","Bei Hormontherapie zählen persönliche Risiken, Beschwerden und Ziele. Die Entscheidung gehört in ein individuelles Arztgespräch.","Blutzuckerschwankungen können Müdigkeit und Heißhunger beeinflussen. Regelmäßige Mahlzeiten mit Protein und Ballaststoffen können stabiler sättigen."],
 en:["Caffeine may worsen hot flashes or sleep for some people. Notice whether you see a pattern in your own entries.","Regular physical activity can support sleep, mood and overall wellbeing. The best routine is one you can realistically sustain.","Hormone therapy decisions depend on personal risks, symptoms and goals and should be individualized with a clinician.","Blood sugar swings can affect fatigue and cravings. Meals with protein and fiber may support steadier satiety."]
};

const evidence={
 de:[["Schlaf","Schlafstörungen sind in der Perimenopause häufig. Hitzewallungen, Stimmung, Stress und hormonelle Veränderungen können zusammenwirken; feste Schlafzeiten und ein kühles Schlafzimmer können helfen."],["Phytoöstrogene & Ernährung","Soja-Isoflavone können bei manchen Frauen vasomotorische Beschwerden leicht reduzieren. Der Effekt ist individuell und ersetzt keine medizinische Behandlung."],["Protein & Muskelmasse","Mit zunehmendem Alter wird der Erhalt von Muskelmasse wichtiger. Ausreichend Protein und Krafttraining können dabei unterstützen, sofern medizinisch nichts dagegenspricht."],["HRT / HET","Eine Hormontherapie kann vasomotorische Beschwerden wirksam lindern, ist aber nicht für jede Person gleich geeignet. Nutzen und Risiken sollten individuell ärztlich besprochen werden."]],
 en:[["Sleep","Sleep problems are common in perimenopause. Hot flashes, mood, stress and hormonal changes can interact; consistent sleep timing and a cooler bedroom may help."],["Phytoestrogens & nutrition","Soy isoflavones may modestly reduce vasomotor symptoms for some women. Effects vary and this does not replace medical treatment."],["Protein & muscle","Maintaining muscle becomes more important with age. Adequate protein and resistance exercise can help when medically appropriate."],["HRT / MHT","Hormone therapy can be effective for vasomotor symptoms, but suitability differs by person. Benefits and risks should be discussed individually with a clinician."]]
};

function blankDraft(){return{sleep:0,energy:0,mood:0,focus:0,physical:[]}}
function clone(v){return JSON.parse(JSON.stringify(v))}
function uid(){return (crypto?.randomUUID?.()||("e_"+Date.now()+"_"+Math.random().toString(16).slice(2)))}
function normalizeEntry(e){return{id:String(e?.id||uid()),ts:new Date(e?.ts||Date.now()).toISOString(),type:e?.type==="acute"?"acute":"checkin",sleep:Number.isFinite(+e?.sleep)?Math.max(0,Math.min(5,+e.sleep)):0,energy:Number.isFinite(+e?.energy)?Math.max(0,Math.min(5,+e.energy)):0,mood:Number.isFinite(+e?.mood)?Math.max(0,Math.min(5,+e.mood)):0,focus:Number.isFinite(+e?.focus)?Math.max(0,Math.min(5,+e.focus)):0,physical:Array.isArray(e?.physical)?e.physical.filter(x=>symptoms.some(s=>s.id===x)):[],acuteSymptom:symptoms.some(s=>s.id===e?.acuteSymptom)?e.acuteSymptom:"",intensity:Number.isFinite(+e?.intensity)?Math.max(1,Math.min(3,+e.intensity)):2}}
function migrate(){let cur=null;try{cur=JSON.parse(localStorage.getItem(KEY)||"null")}catch{}if(cur&&cur.schemaVersion===VERSION){cur.entries=Array.isArray(cur.entries)?cur.entries.map(normalizeEntry):[];return{...clone(defaultState),...cur}}const next=clone(defaultState);const legacy=["midlifeOS_v12","midlifeOS_v10","midlifeOS_v9","midlifeOS_v8","midlifeOS_v7"];for(const key of legacy){try{const old=JSON.parse(localStorage.getItem(key)||"null");if(!old)continue;if(old.lang==="de"||old.lang==="en")next.lang=old.lang;if(Array.isArray(old.entries)){for(const e of old.entries){const phys=[];if(e.values?.hot&&e.values.hot!=="none")phys.push("hot");if(e.values?.joints&&e.values.joints!=="none")phys.push("joints");if(e.values?.headache&&e.values.headache!=="none")phys.push("headache");if(e.values?.palpitations&&e.values.palpitations!=="none")phys.push("palpitations");next.entries.push(normalizeEntry({id:uid(),ts:e.ts,type:e.kind==="acute-hot-flash"?"acute":"checkin",acuteSymptom:e.kind==="acute-hot-flash"?"hot":"",physical:phys,intensity:e.values?.hot==="strong"?3:e.values?.hot==="light"?1:2}))}}}catch{}}localStorage.setItem(KEY,JSON.stringify(next));return next}
function load(){return migrate()}
function save(){state.schemaVersion=VERSION;localStorage.setItem(KEY,JSON.stringify(state))}
function tr(k){return text[state.lang][k]||k}
function symName(id){const s=symptoms.find(x=>x.id===id);return s?(state.lang==="de"?s.de:s.en):id}
function sameDay(a,b=new Date()){const d=new Date(a);return d.getFullYear()===b.getFullYear()&&d.getMonth()===b.getMonth()&&d.getDate()===b.getDate()}
function todayEntries(){return state.entries.filter(e=>sameDay(e.ts)).sort((a,b)=>new Date(b.ts)-new Date(a.ts))}
function cutoff(days){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-(days-1));return d}
function inRange(days){const c=cutoff(days);return state.entries.filter(e=>new Date(e.ts)>=c).sort((a,b)=>new Date(a.ts)-new Date(b.ts))}
function greeting(){const h=new Date().getHours();return h<11?tr("greetMorning"):h<18?tr("greetDay"):tr("greetEvening")}
function showToast(msg){document.querySelector(".toast")?.remove();const e=document.createElement("div");e.className="toast";e.textContent=msg;document.body.appendChild(e);if(navigator.vibrate)navigator.vibrate(20);setTimeout(()=>e.remove(),1800)}
function lineIcon(kind){const p={home:'<path d="M4 11.5 12 5l8 6.5V20H4z"/><path d="M9 20v-6h6v6"/>',plus:'<path d="M12 5v14M5 12h14"/>',book:'<path d="M4 5.5A3.5 3.5 0 0 1 7.5 2H12v18H7.5A3.5 3.5 0 0 0 4 23z"/><path d="M20 5.5A3.5 3.5 0 0 0 16.5 2H12v18h4.5A3.5 3.5 0 0 1 20 23z"/>',report:'<path d="M6 3h9l3 3v15H6z"/><path d="M15 3v4h4M9 12h6M9 16h6"/>'}[kind];return `<svg viewBox="0 0 24 24" aria-hidden="true">${p}</svg>`}
function render(){document.documentElement.lang=state.lang;document.getElementById("app").innerHTML=`<div class="app-shell"><header class="topbar"><div class="brand">Midlife <b>OS.</b></div><div class="lang"><button data-lang="de" class="${state.lang==="de"?"active":""}">DE</button><button data-lang="en" class="${state.lang==="en"?"active":""}">EN</button></div></header><main class="view">${viewHtml()}</main><nav class="bottom-nav"><button data-tab="dashboard" class="${state.activeTab==="dashboard"?"active":""}">${lineIcon("home")}<span>${tr("dashboard")}</span></button><button data-tab="log" class="${state.activeTab==="log"?"active":""}">${lineIcon("plus")}<span>${tr("log")}</span></button><button data-tab="tools" class="${state.activeTab==="tools"?"active":""}">${lineIcon("book")}<span>${tr("tools")}</span></button><button data-tab="report" class="${state.activeTab==="report"?"active":""}">${lineIcon("report")}<span>${tr("report")}</span></button></nav></div>`;bindGlobal();bindView()}
function viewHtml(){if(state.activeTab==="log")return logHtml();if(state.activeTab==="tools")return toolsHtml();if(state.activeTab==="report")return reportHtml();return dashboardHtml()}
function dashboardHtml(){const today=todayEntries(),week=inRange(7),trend=trendSeries(7),trackedDays=new Set(week.map(e=>e.ts.slice(0,10)));const dayCells=[];const base=new Date();for(let i=-6;i<=0;i++){const d=new Date(base);d.setDate(base.getDate()+i);const key=d.toISOString().slice(0,10);dayCells.push(`<div class="week-day ${trackedDays.has(key)?"tracked":""} ${i===0?"today":""}"><span>${d.toLocaleDateString(state.lang==="de"?"de-DE":"en-GB",{weekday:"narrow"})}</span><b>${d.getDate()}</b></div>`)}const tip=tips[state.lang][new Date().getDate()%tips[state.lang].length];return `<div class="stack"><div class="header-status"><div class="eyebrow">${tr("dashboard")}</div><h1>${greeting()}</h1><div class="status-line">${today.some(e=>e.type==="checkin")?tr("checked"):tr("noCheck")}</div></div><div class="quick-grid"><button class="quick-card sos" id="openSos"><strong>${tr("sos")}</strong><small>${tr("sosSub")}</small></button><button class="quick-card" data-go="log"><strong>${tr("checkin")}</strong><small>${tr("checkinSub")}</small></button></div><section class="card week-card"><div class="row"><div><div class="eyebrow">${tr("week")}</div><h2>${week.length} ${tr("entries")}</h2></div><span class="pill">${trackedDays.size}/7</span></div><div class="week-days">${dayCells.join("")}</div><div class="mini-chart">${svgTrend(trend)}</div></section><div class="tip"><strong>${tr("tip")}</strong><div style="margin-top:4px">${tip}</div></div></div>`}
function logHtml(){return `<div class="stack"><div><div class="eyebrow">${tr("log")}</div><h1>${tr("checkin")}</h1><p class="sub">${tr("checkinSub")}</p></div><section class="card log-section"><div><div class="eyebrow">${tr("sleepEnergy")}</div></div>${scaleBlock("sleep",tr("sleep"))}${scaleBlock("energy",tr("energy"))}</section><section class="card log-section"><div class="eyebrow">${tr("moodFocus")}</div>${scaleBlock("mood",tr("mood"))}${scaleBlock("focus",tr("focus"))}</section><section class="card"><div class="eyebrow">${tr("physical")}</div><div class="chips" style="margin-top:10px">${symptoms.map(s=>`<button class="chip ${draft.physical.includes(s.id)?"active":""}" data-phys="${s.id}">${symName(s.id)}</button>`).join("")}</div></section><button class="primary" id="saveCheckin">${tr("save")}</button></div>`}
function scaleBlock(key,label){return `<div class="scale-row"><div class="row"><strong>${label}</strong><span class="pill">${draft[key]?draft[key]+"/5":"—"}</span></div><div class="scale-buttons">${[1,2,3,4,5].map(n=>`<button data-scale="${key}:${n}" class="${draft[key]===n?"active":""}">${n}</button>`).join("")}</div></div>`}
function toolsHtml(){const snacks=evidence[state.lang].map(([a,b])=>`<div class="snack"><strong>${a}</strong><p>${b}</p></div>`).join("");return `<div class="stack"><div><div class="eyebrow">${tr("tools")}</div><h1>${tr("breathe")}</h1><p class="sub">${tr("breatheSub")}</p></div><section class="tool-card"><div class="breathe"><div class="breathe-circle" id="breathCircle"><div><strong id="breathLabel">${tr("inhale")}</strong><span id="breathCount">4</span></div></div></div><button class="primary" id="breathToggle">${breathingRunning?tr("stop"):tr("start")}</button></section><section class="tool-card"><div class="eyebrow">${tr("evidence")}</div><div class="snack-list" style="margin-top:10px">${snacks}</div></section><div class="medical-note">${tr("medical")}</div></div>`}
function reportHtml(){const range=state.reportRange,entries=inRange(range),stats=symptomStats(entries),bleeds=entries.filter(e=>e.physical.includes("bleeding")||e.acuteSymptom==="bleeding");return `<div class="stack report-only"><div><div class="eyebrow">${tr("report")}</div><h1>${tr("analysis")}</h1><p class="sub">${tr("medical")}</p></div><div class="report-tabs no-print">${[30,60,90].map(n=>`<button data-report-range="${n}" class="${range===n?"active":""}">${n} ${state.lang==="de"?"Tage":"days"}</button>`).join("")}</div><section class="card"><div class="row"><div><div class="eyebrow">${tr("period")}</div><h2>${range} ${state.lang==="de"?"Tage":"days"}</h2></div><span class="pill">${entries.length} ${tr("entries")}</span></div></section><section class="card"><table class="table"><thead><tr><th>${tr("symptom")}</th><th>${tr("frequency")}</th><th>${tr("avg")}</th></tr></thead><tbody>${stats.length?stats.slice(0,5).map(x=>`<tr><td>${symName(x.id)}</td><td>${x.count}</td><td>${x.avg.toFixed(1)}</td></tr>`).join(""):`<tr><td colspan="3">${tr("noData")}</td></tr>`}</tbody></table></section><section class="card"><div class="eyebrow">${tr("cycle")}</div><div class="sub" style="margin-top:7px">${bleeds.length?`${bleeds.length} ${state.lang==="de"?"dokumentierte Blutungs-/Schmierblutungs-Ereignisse":"documented bleeding/spotting events"}`:tr("noData")}</div></section><section class="card"><div class="eyebrow">${tr("patientNotes")}</div><textarea class="notes" id="doctorNote" placeholder="${tr("patientNotes")}">${escapeHtml(state.doctorNote||"")}</textarea></section><section class="card"><div class="eyebrow">${tr("doctorNotes")}</div><div style="min-height:90px;border-bottom:1px solid #CBD5E1"></div></section><button class="primary no-print" id="printReport">${tr("print")}</button></div>`}
function symptomStats(entries){const map={};for(const e of entries){const ids=e.type==="acute"&&e.acuteSymptom?[e.acuteSymptom]:e.physical;for(const id of ids){map[id]??={count:0,sum:0};map[id].count++;map[id].sum+=e.type==="acute"?e.intensity:1}}return Object.entries(map).map(([id,v])=>({id,count:v.count,avg:v.sum/v.count})).sort((a,b)=>b.count-a.count)}
function trendSeries(days){const start=cutoff(days),arr=[];for(let i=0;i<days;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=d.toISOString().slice(0,10);const count=state.entries.filter(e=>e.ts.slice(0,10)===key).length;arr.push({date:d,value:count})}return arr}
function svgTrend(series){const w=340,h=110,p=16,max=Math.max(1,...series.map(x=>x.value));const pts=series.map((d,i)=>({x:p+i*((w-2*p)/Math.max(1,series.length-1)),y:h-p-(d.value/max)*(h-2*p)}));const line=pts.map(q=>`${q.x},${q.y}`).join(" ");const area=`${p},${h-p} ${line} ${w-p},${h-p}`;return `<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><polyline class="chart-area" points="${area}"></polyline><polyline class="chart-line" points="${line}"></polyline></svg>`}
function bindGlobal(){document.querySelectorAll("[data-lang]").forEach(b=>b.onclick=()=>{state.lang=b.dataset.lang;save();render()});document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{stopBreathing();state.activeTab=b.dataset.tab;save();render()});document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>{state.activeTab=b.dataset.go;save();render()});document.getElementById("openSos")?.addEventListener("click",openSos)}
function bindView(){document.querySelectorAll("[data-scale]").forEach(b=>b.onclick=()=>{const [k,n]=b.dataset.scale.split(":");draft[k]=Number(n);render()});document.querySelectorAll("[data-phys]").forEach(b=>b.onclick=()=>{const id=b.dataset.phys;draft.physical=draft.physical.includes(id)?draft.physical.filter(x=>x!==id):[...draft.physical,id];render()});document.getElementById("saveCheckin")?.addEventListener("click",saveCheckin);document.getElementById("breathToggle")?.addEventListener("click",toggleBreathing);document.querySelectorAll("[data-report-range]").forEach(b=>b.onclick=()=>{state.reportRange=Number(b.dataset.reportRange);save();render()});document.getElementById("doctorNote")?.addEventListener("input",e=>{state.doctorNote=e.target.value;save()});document.getElementById("printReport")?.addEventListener("click",()=>window.print())}
function saveCheckin(){if(!draft.sleep&&!draft.energy&&!draft.mood&&!draft.focus&&!draft.physical.length){showToast(state.lang==="de"?"Bitte mindestens einen Wert auswählen.":"Please choose at least one value.");return}state.entries.push(normalizeEntry({id:uid(),ts:new Date(),type:"checkin",...draft}));save();draft=blankDraft();showToast(tr("saved"));state.activeTab="dashboard";save();setTimeout(render,220)}
function openSos(){sosChoice="";const wrap=document.createElement("div");wrap.className="sos-sheet-backdrop";wrap.id="sosModal";wrap.innerHTML=`<section class="sheet"><div class="grabber"></div><div class="sheet-head"><div><div class="eyebrow">${tr("sos")}</div><h2>${tr("chooseSymptom")}</h2></div><button class="close" id="closeSos">×</button></div><div class="sos-options">${["hot","headache","palpitations","bleeding"].map(id=>`<button class="sos-option" data-sos="${id}">${symName(id)}</button>`).join("")}</div><button class="primary" id="saveSos" style="margin-top:12px">${tr("saveSos")}</button></section>`;document.body.appendChild(wrap);wrap.onclick=e=>{if(e.target===wrap)wrap.remove()};wrap.querySelector("#closeSos").onclick=()=>wrap.remove();wrap.querySelectorAll("[data-sos]").forEach(b=>b.onclick=()=>{sosChoice=b.dataset.sos;wrap.querySelectorAll("[data-sos]").forEach(x=>x.classList.toggle("active",x.dataset.sos===sosChoice))});wrap.querySelector("#saveSos").onclick=()=>{if(!sosChoice)return;state.entries.push(normalizeEntry({id:uid(),ts:new Date(),type:"acute",acuteSymptom:sosChoice,intensity:2}));save();wrap.remove();showToast(tr("sosSaved"));render()}}
function toggleBreathing(){breathingRunning?stopBreathing(true):startBreathing()}
function startBreathing(){breathingRunning=true;let phase=0;const phases=[{key:"inhale",sec:4,cls:"expand"},{key:"hold",sec:7,cls:"hold"},{key:"exhale",sec:8,cls:"contract"}];const run=()=>{if(!breathingRunning)return;const p=phases[phase%3],circle=document.getElementById("breathCircle"),label=document.getElementById("breathLabel"),count=document.getElementById("breathCount");if(!circle||!label||!count)return;circle.className="breathe-circle "+p.cls;label.textContent=tr(p.key);let left=p.sec;count.textContent=left;clearInterval(breathingTimer);breathingTimer=setInterval(()=>{left--;if(left<=0){clearInterval(breathingTimer);phase++;run()}else count.textContent=left},1000)};render();setTimeout(run,20)}
function stopBreathing(rerender=false){breathingRunning=false;clearInterval(breathingTimer);breathingTimer=null;if(rerender)render()}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}

render();
})();
