(()=>{"use strict";
const KEYS=["midlifeOS_v8","midlifeOS_v7"];
function readState(){for(const k of KEYS){try{const raw=localStorage.getItem(k);if(raw)return{k,data:JSON.parse(raw)}}catch{}}return{k:"midlifeOS_v7",data:{lang:"de"}}}
function currentLang(){return readState().data.lang||"de"}
function de(){return currentLang()==="de"}
function svg(type){const p={help:'<circle cx="12" cy="12" r="9"/><path d="M9.8 9a2.4 2.4 0 1 1 3.9 1.9c-1 .7-1.7 1.2-1.7 2.6M12 17h.01"/>',trash:'<path d="M4 7h16M9 7V4h6v3M7 7l1 13h8l1-13M10 10v6M14 10v6"/>',lock:'<rect x="5" y="10" width="14" height="10" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/>'};return `<svg class="lineicon" viewBox="0 0 24 24" aria-hidden="true">${p[type]||p.help}</svg>`}
function restoreIfTrapped(){const s=readState();const d=s.data||{};if(d.onboarded===false&&Number(d.step)>1&&d.entries&&Object.keys(d.entries).length>0){d.onboarded=true;d.step=1;localStorage.setItem(s.k,JSON.stringify(d));location.reload()}}
function fixLanding(){const hero=document.querySelector(".hero");if(!hero||hero.dataset.v9)return;hero.dataset.v9="1";hero.classList.remove("hero-photo");hero.querySelector(".hero-overlay")?.remove();const content=hero.querySelector(".heroin");if(!content)return;let media=hero.querySelector(".hero-media-v9");if(!media){media=document.createElement("div");media.className="hero-media-v9";media.setAttribute("role","img");media.setAttribute("aria-label",de()?"Portrait einer Frau":"Portrait of a woman");hero.prepend(media)}content.classList.add("hero-content-v9");const sub=content.querySelector(".sub");if(sub)sub.classList.remove("hero-sub");const trust=content.querySelector(".trust");if(trust){trust.innerHTML=`${svg("lock")}<span>${de()?"100% lokal auf deinem Gerät · Kein Konto nötig":"100% local on your device · No account needed"}</span>`}}
function tourModal(){if(document.querySelector("#tourV9Modal"))return;const m=document.createElement("div");m.className="modal";m.id="tourV9Modal";m.innerHTML=`<section class="sheet tour-v9"><div class="sheethead"><div><div class="kicker">${de()?"App-Tour & Hilfe":"App tour & help"}</div><h2>${de()?"So funktioniert Midlife OS":"How Midlife OS works"}</h2></div><button class="close" id="tourV9Close" aria-label="Close">×</button></div><div class="tour-steps-v9"><div><b>1</b><span><strong>${de()?"30 Sekunden täglich":"30 seconds a day"}</strong><small>${de()?"Drei Fokus-Symptome kurz bewerten und speichern.":"Rate your three focus symptoms and save."}</small></span></div><div><b>2</b><span><strong>${de()?"Muster erkennen":"See patterns"}</strong><small>${de()?"Nach mehreren Einträgen werden nur echte Trends aus deinen Daten sichtbar.":"After several check-ins, only real trends from your data appear."}</small></span></div><div><b>3</b><span><strong>${de()?"Arztgespräch vorbereiten":"Prepare your appointment"}</strong><small>${de()?"Die wichtigsten Punkte kompakt als Bericht zusammenfassen.":"Summarize the most important points in a clear report."}</small></span></div></div><button class="primary" id="tourV9Done">${de()?"Verstanden":"Got it"}</button></section>`;document.body.appendChild(m);const close=()=>m.remove();m.querySelector("#tourV9Close").onclick=close;m.querySelector("#tourV9Done").onclick=close}
function resetModal(){if(document.querySelector("#resetV9Modal"))return;const m=document.createElement("div");m.className="modal";m.id="resetV9Modal";m.innerHTML=`<section class="sheet"><div class="sheethead"><h2>${de()?"App vollständig zurücksetzen":"Reset app completely"}</h2><button class="close" id="resetV9Close">×</button></div><p class="sub">${de()?"Alle gespeicherten Einträge, Symptome und Einstellungen auf diesem Gerät werden dauerhaft gelöscht. Das kann nicht rückgängig gemacht werden.":"All saved entries, symptoms and settings on this device will be permanently deleted. This cannot be undone."}</p><div class="modal-actions"><button class="secondary" id="resetV9Cancel">${de()?"Abbrechen":"Cancel"}</button><button class="danger-btn" id="resetV9Confirm">${de()?"Alles löschen":"Delete everything"}</button></div></section>`;document.body.appendChild(m);const close=()=>m.remove();m.querySelector("#resetV9Close").onclick=close;m.querySelector("#resetV9Cancel").onclick=close;m.querySelector("#resetV9Confirm").onclick=()=>{KEYS.forEach(k=>localStorage.removeItem(k));navigator.serviceWorker?.getRegistrations?.().then(rs=>rs.forEach(r=>r.unregister()));location.reload()}}
function fixProfile(){const h=[...document.querySelectorAll("h1")].find(x=>/Mein Midlife OS|My Midlife OS/.test(x.textContent||""));if(!h)return;const stack=h.closest(".stack");if(!stack)return;const old=document.querySelector("#introV8");if(old&&!document.querySelector("#tourV9")){const n=old.cloneNode(true);n.id="tourV9";n.querySelector("strong").textContent=de()?"App-Tour & Hilfe":"App tour & help";n.querySelector("small").textContent=de()?"Funktionen kurz erklären – ohne die Einrichtung neu zu starten.":"A quick explanation without restarting setup.";n.querySelector(".ico").innerHTML=svg("help");old.replaceWith(n);n.onclick=tourModal}
if(!document.querySelector("#tourV9")){const advanced=stack.querySelector("#advanced");const n=document.createElement("button");n.className="setting";n.id="tourV9";n.innerHTML=`<span class="ico">${svg("help")}</span><span><strong>${de()?"App-Tour & Hilfe":"App tour & help"}</strong><small>${de()?"Funktionen kurz erklären – ohne die Einrichtung neu zu starten.":"A quick explanation without restarting setup."}</small></span><span>›</span>`;n.onclick=tourModal;advanced?advanced.before(n):stack.append(n)}
let reset=document.querySelector("#resetV8")||document.querySelector("#resetV9");if(reset){const n=reset.cloneNode(true);n.id="resetV9";reset.replaceWith(n);n.onclick=resetModal}else{reset=document.createElement("button");reset.className="setting danger";reset.id="resetV9";reset.innerHTML=`<span class="ico">${svg("trash")}</span><span><strong>${de()?"App vollständig zurücksetzen":"Reset app completely"}</strong><small>${de()?"Löscht alle Einträge und Einstellungen auf diesem Gerät.":"Deletes all entries and settings on this device."}</small></span><span>›</span>`;reset.onclick=resetModal;stack.append(reset)}}
function fixKnowledge(){document.querySelectorAll(".accordion").forEach((a,i)=>{const title=(a.querySelector("button")?.textContent||"").toLowerCase();const body=a.querySelector(".body");if(!body)return;if(title.includes("perimenopause"))body.textContent=de()?"Die Perimenopause ist die Übergangszeit vor der letzten Menstruation. Zyklus, Schlaf, Stimmung und Wärmeempfinden können sich dabei verändern.":"Perimenopause is the transition before the final menstrual period. Cycle, sleep, mood and temperature regulation can change during this time.";else if(title.includes("schlaf")||title.includes("sleep"))body.textContent=de()?"Schlafprobleme und Hitzewallungen können gemeinsam auftreten. Deine Einträge helfen dir zu sehen, ob sich bei dir zeitliche Muster zeigen.":"Sleep problems and hot flashes can occur together. Your entries help you see whether a timing pattern appears for you.";else if(title.includes("hormon")||title.includes("hormone"))body.textContent=de()?"Hormontherapie kann unterschiedliche Formen haben, z. B. Östrogen-Gel oder -Pflaster und Progesteron. Midlife OS dokumentiert nur, was du bereits verwendest oder ärztlich besprochen hast.":"Hormone therapy can include estrogen gel or patches and progesterone. Midlife OS only records what you already use or have discussed with a clinician."})}
function fixLanguage(){document.querySelectorAll(".lang").forEach(el=>{el.classList.add("lang-v9");el.setAttribute("aria-label",de()?"Sprache wechseln":"Switch language")})}
function patch(){fixLanding();fixProfile();fixKnowledge();fixLanguage()}
restoreIfTrapped();const mo=new MutationObserver(patch);mo.observe(document.documentElement,{childList:true,subtree:true});patch();
})();